[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default.csv
build_flags =
  -D CORE_DEBUG_LEVEL=3
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  ESP32Async/ESPAsyncWebServer @ ^3.6.0
  ESP32Async/AsyncTCP @ ^3.3.2
